name: mood_tracker
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^15.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  lottie: ^3.3.1
  pie_chart: ^5.4.0
  uuid: ^4.5.1
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/nodata.json
    - assets/images2/
    # - assets/imagesnoBg/
